export default {
    PRIOR_BUY_LIST:'PRIOR_BUY_LIST',
    COUPONS_LIST:'COUPONS_LIST',
    EXCLUSIVE_LIST:'EXCLUSIVE_LIST',
    DISCOUNT_LIST:"DISCOUNT_LIST",
    WATCH_PER_LIST:'WATCH_PER_LIST',
    WATCH_PRO_INFO:'WATCH_PRO_INFO'
}