export default {
    UP_REGISTER_COUPON:'UP_REGISTER_COUPON',
    UP_CLASSIFY_HOME:'UP_CLASSIFY_HOME',
    UP_HOTS_RECOMMEND_LIST:'UP_HOTS_RECOMMEND_LIST',
    UP_FLOOR_SHOW:'UP_FLOOR_SHOW',
    UP_RECOMMEND_SHOW:'UP_RECOMMEND_SHOW',
    UP_VIP_HOME_SCHEDULAR:'UP_VIP_HOME_SCHEDULAR',
    UP_HOT_THEATRE:'UP_HOT_THEATRE',
    UP_TOUR_RECOMMEND_LIST:'UP_TOUR_RECOMMEND_LIST'
}